project:
  type: book
  output-dir: docs

book:
  title: "Modul Teknik Pengumpulan Data"
  author: "Muhammad Ammar Sahab"
  date: "9/22/2022"
  chapters:
    - index.qmd
    - 1-Review.qmd
    - 2-Terminologi.qmd
    - 3-SimpleRandom.qmd
    - 4-Stratified.qmd
    - 5-Systematic.qmd
    - 6-Cluster.qmd

bibliography: references.bib

format:
  html:
    theme: simplex



